### ISSUE TITLE
Can't send dai 

### ISSUE THREAD

**Issue by GriffGreen** [austintgriffith/burner-wallet#102]
I would love an Easter egg or even full on functionality to switch networks and use xdai.io for moving dai as welll... If that functionality exists... I can't find it

**Comment by TimDaub** [comment]
Hi @GriffGreen, this feature exists (now). Click the buttons with the arrows pointing to the "right".

<img width="754" alt="Screen Shot 2019-06-04 at 12 13 10" src="https://user-images.githubusercontent.com/2758453/58871375-225fec80-86c2-11e9-98dd-a5a301374532.png">
