### ISSUE TITLE
Smaller top level action surface area - clearer focus UX

### ISSUE THREAD

**Issue by winfred** [austintgriffith/burner-wallet#110]
I enjoy thinking about UX. I could also code these changes if I get the time and you like the direction. (Was just wireframing in Chrome debugger for these.)

## Simplify home screen.

* Move the alternate CTAs to the top, further away from thumbs (optimizing for mobile)
  * maybe even move advanced to the top? (theme: keep primary CTAs close to bottom for thumbs)
* Squeezing the buttons in on the left & right with padding
  * gives a warmer diamond shape, less cold/grid-like. Could maybe even squeeze it some more.
* Move "Link" and "Request" 
  * "Link" is part of "Send"
  * "Request" is part of "Receive"

![screen shot 2019-03-01 at 9 44 54 pm](https://user-images.githubusercontent.com/169076/53676674-5236c880-3c6b-11e9-8bf6-ebc75cd98611.png)

### Link in Send
_note the QR scanner button is larger, easier to tap_
![screen shot 2019-03-01 at 9 19 40 pm](https://user-images.githubusercontent.com/169076/53676452-1817f780-3c68-11e9-967c-91b25bf9f340.png)

### Request in Receive
![screen shot 2019-03-01 at 9 37 16 pm](https://user-images.githubusercontent.com/169076/53676681-814d3a00-3c6b-11e9-88d6-ad75293c4436.png)

## What do you think?
That "leave blank" UX hack... clever? confusing?
It does give us a simplicity win on the homescreen for sure, and in theory more toggles/buttons could be added to the secondary panels should the "leave blank" hack not suffice. But at the moment it feels elegant to me.

**Comment by winfred** [comment]
Ha, this is pretty much what daicard.io has done.

I am clearly already out of the loop. 🤷‍♂️

**Comment by TimDaub** [comment]
Hi @winfred, thanks for your input!

I thought about this idea for a while. My personal opinion is that I think there's more mental overhead for the user in understanding that e.g. leaving the address field in a Send action blank will spawn the Link functionality. Same goes for Request and Receive. I'm especially concerned for users that are new to crypto, as I don't think they'll be able to make this leap in understanding quickly.

I like however your idea of making buttons more accessible to touch screen users. I created an issue for this: #201

@austintgriffith Maybe you can comment on whether we want to combine Request/Receive and Send/Link.
