### ISSUE TITLE
QR code partially loads

### ISSUE THREAD

**Issue by peter-boot** [austintgriffith/burner-wallet#12]
May be due to an under powered phone but QR code only partially loads on both Android Chrome & Brave browsers.  Phone HTC One, Android 5.0.2
![screenshot_2018-11-10-06-52-58](https://user-images.githubusercontent.com/753883/48293429-25e81800-e4d3-11e8-958c-1e998e92bb32.png)

**Comment by austintgriffith** [comment]
Can anyone else replicate this? I can't even figure out how to debug this! Would love some input from the community.

**Comment by peter-boot** [comment]
Yes no longer happening
