### ISSUE TITLE
auto-Localization issue with xdai.io

### ISSUE THREAD

**Issue by marczeller** [austintgriffith/burner-wallet#128]
Xdai.io several times in different devices is booted with the new hebrew translation localisation as default. that's cool for the users using that as their primary language

but as this is not an alphabet-based language it's a rather-confusing experience for everybody else!

Issue occurred on several devices and on chrome browser.
local language of the device was Portuguese, so expected behaviour was a default english-based localization.

i think it's might be an issue related to the recent hebrew PR :) link here : https://github.com/austintgriffith/burner-wallet/pull/118

good luck finding the bug!

![20190404_201350](https://user-images.githubusercontent.com/21088542/55670585-52d00980-587e-11e9-980b-8dfa10218bba.jpg)
![20190404_201358](https://user-images.githubusercontent.com/21088542/55670586-52d00980-587e-11e9-8a86-2f80f211ce37.jpg)
![20190406_142141](https://user-images.githubusercontent.com/21088542/55670587-52d00980-587e-11e9-9dc6-df7155ddef34.jpg)
![20190406_142146](https://user-images.githubusercontent.com/21088542/55670588-5368a000-587e-11e9-856c-f8916873168e.jpg)

**Comment by tomislavmamic** [comment]
I initialized a wallet today and this happened. https://nimb.ws/1qY9u5

**Comment by marczeller** [comment]
@tomislavmamic may i ask what's your device current language setting and OS?

My empiric-based guess for this bug is that if the device is not setup to one of the main localization 
language, (EN-ES-FR-DE-CA it'll set it to Hebrew as some "default-language".
@austintgriffith

**Comment by mkosowsk** [comment]
@austintgriffith may make sense to have EN as `default-language` if @marczeller is on the right path (and I think he is 👍)

**Comment by marczeller** [comment]
@mkosowsk that's the hard part then bacause the fallback is set to EN : 
![image](https://user-images.githubusercontent.com/21088542/56126740-83492f00-5f73-11e9-812f-abb83ec3f597.png)

so i'm really clueless here.

**Comment by mkosowsk** [comment]
@marczeller really got me scratching my head too 🤔

It must be some type of override then I guess, but where? 🤔

**Comment by marczeller** [comment]
https://github.com/austintgriffith/burner-wallet/commit/1a004c92ae90876292b7f15d247d32e17730745d

that commit didn't worked 😂

**Comment by tomislavmamic** [comment]
This is still happening. I was with a vendor today and his wallet initiated with the Hebrew language.
It's quite urgent to solve this as we have an event happening in 2 days. Can you please resolve this?
