### ISSUE TITLE
Signer may send a signature valid for both send() and claim()

### ISSUE THREAD

**Issue by catageek** [austintgriffith/burner-wallet#13]
In send(), the signer signs bytes32 Id, but if the Id is chosen to be equal to keccak256(destination), then the data and signature are identical in send() and claim(): both refer to keccak256(destination) as data.

So the issue is how the Id is generated, and if it is controlled by a third-party, it can be set to a specifically crafted value of keccak256(address_attacker) and submitted to the signer. The signature can then be used by the attacker in claim() after 100 blocks.

Legitimate users are at risk of being robbed by a malicous third-party generating Id on their behalf.

The fix is, for example, to sign keccak(Id, "CONSTANT") instead of Id to make the signed data unpredictable.

**Comment by austintgriffith** [comment]
Sorry for the long delay. What is the status of this issue? Should we put a PR in on the contract?
