### ISSUE TITLE
The signature submitted in claim() can be reused multiple times

### ISSUE THREAD

**Issue by catageek** [austintgriffith/burner-wallet#14]
The signature in claim() refers only to the destination address.

So, once a valid signature has been published for a specific destination, It can be reused to claim all the funds for any Id where funds[Id].signer is the same signer.

I am not sure that it is or not the intention of the developper, but we can have N send() from one signer, then 1 claim() with its signature and we can generate immediately the N-1 claim() to the same destination.

I propose to sign keccak256(Id, address) to prevent this replay attack.

**Comment by riusricardo** [comment]
I do not think it's a replay attack for the scope of this contract. It is a type of vault, so it is correct to have access to the funds where you are a signer.
My doubt is about what happens when it expires. It is not clear. Up to now it looks like it remains locked in the contract.

**Comment by catageek** [comment]
I confirm that there is a replay attack.
Let H be a holder and C be the claimer.

1. H calls send(id1, sig1) where sig1 has been signed by himself
2. H signs keccak256(address(C)) = **sig2** and publishes sig2 offline
3. Someone (C ?) calls Claim(id1, **sig2**, address(C))
4. if (sig1and sig2) are signed by H, then transfer(some ETH) to C

Later, H wants to reuse the wallet but to transfer funds to Z. C is not in the process.
5. H calls send(id2, sig3) where sig3 has been signed by himself
6. C has observed the previous tx and calls Claim(id2, **sig2**, address(C)) immediately
7. if (sig3 and sig2) are signed by H (this is the case), then **transfer(some ETH) to C**.

At step 6, C replays sig2 that was part of the previous cycle, and steals the funds of Z.
It means that each time H wants to reuse the wallet, C will take the funds by replaying sig2 again and again.

**Comment by riusricardo** [comment]
Ok, I agree. It is a replay attack and a possible case for this contract. This contract should have similar mechanisms to an EOA. It should have a nonce that increases on every send transaction.

**Comment by austintgriffith** [comment]
Just doubled up the bounty on the audit and I want to make sure we reward the active audit of the contract. @riusricardo and @catageek could you guys him me up on Twitter or Telegram @austingriffith so I can make direct contact?

**Comment by catageek** [comment]
I'm ktageek on twitter (not catageek, already taken). Following you now.
