### ISSUE TITLE
Coinmarketcap API endpoint is deprecated

### ISSUE THREAD

**Issue by morelazers** [austintgriffith/burner-wallet#146]
Navigating to [one of the API endpoints used by the Burner wallet](https://api.coinmarketcap.com/v2/ticker/1027/), there's a deprecation message.

Is there a better alternative to Coinmarketcap? I see they have a free tier but it looks like you'd have to get burner devs to sign up for an API account.

Will submit a PR to use a different API if anyone knows of one.

## Roles
bounty gardener: name / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by tmlee** [comment]
@morelazers i suggest trying out our API offerings at https://www.coingecko.com/en/api
its public and no keys required. happy to answer any questions as well!

**Comment by riusricardo** [comment]
@austintgriffith we need to migrate to the new API or maybe use another one. I don't  know how long this Coinmarketcap legacy API will be online.

**"WARNING: This API is now deprecated and will be taken offline soon.  Please switch to the new CoinMarketCap API to avoid interruptions in service. (https://pro.coinmarketcap.com/migrate/)"**

**Comment by TimDaub** [comment]
We changed this here already to the uniswap analytics API: https://github.com/leapdao/burner-wallet/commit/33a767b06dff86a439940adc95c183519129d1f5

If there's interest, I can send a PR with this commit.

**Comment by TimDaub** [comment]
This has become a problem again. At the moment dai.io is not showing ETH balances as they become NaN with coinmarketcap blocking our xdai.io's request.

**Comment by TimDaub** [comment]
This is now a proposed issue for [Sprint 1](https://github.com/austintgriffith/burner-wallet/milestone/1):

Scope and Deliverables: Comments above

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by tmlee** [comment]
@TimDaub wonder if you have had the chance to poke at the CoinGecko API to see if it resolves your pricing issue? ETH price can be pulled directly using https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd

**Comment by mkosowsk** [comment]
Interesting issue and I'm also interested in how the first sprint turns out @TimDaub!

I may hop into some issues here and there, I've got some engineering cycles at the moment (want to finish a Gitcoin PR first tho)

**Comment by dmihal** [comment]
The burner-core already uses it's own price feed, so I believe this switch will be part of the burner-core integrations.

The relevant part of the code is here:
https://github.com/austintgriffith/burner-core/blob/develop/assets/src/pricefeed.js

Currently it uses the CryptoCompare API, but I'd be happy to change to a different API if people think it would be better.

**Comment by austintgriffith** [comment]
I think we decided to ignore this issue because we will be replacing it in the code with the burner-core module right?
