### ISSUE TITLE
How to build it with dapparatus?

### ISSUE THREAD

**Issue by PeterTheOne** [austintgriffith/burner-wallet#183]
```
Failed to compile.

./src/App.js
Module not found: Can't resolve 'dapparatus' in '/home/username/Projects/burner-wallet/src'
```
Do I need to build dapparatus beforehand?

**Comment by PeterTheOne** [comment]
Ok, seems to only be a problem when I directly use the github repository as a dependency and not the npm pacakge..

**Comment by TimDaub** [comment]
> Do I need to build dapparatus beforehand?

> Ok, seems to only be a problem when I directly use the github repository as a dependency and not the npm pacakge..

Exactly. The dapparatus github repository doesn't come with a build included. Then npm package should come with one. Closing this. Feel free to reopen if the issue persists.
