### ISSUE TITLE
Adding: Request Funds functionality

### ISSUE THREAD

**Issue by drhus** [austintgriffith/burner-wallet#19]
use case like pizza restaurant with friends I paid with my credit card, and then I could xdai.io >> request funds >> I enter the amount and possibly a message, and share the link on WhatsApp maybe? or by QR ..

ideally, that *request fund* shall generate a URL >> which if opened in web3 wallet would auto-populate the amount and receiver address, if not just QR code/Wallet address like:

xDAI:0x0000000000000000000?amount=5.6&message=Payment-Piza&label=devcon&extra=other-param

**Comment by austintgriffith** [comment]
Requesting funds with a link is a great idea. Would love to see someone build this out.
