### ISSUE TITLE
Unable to transfer from POA bridge to burner

### ISSUE THREAD

**Issue by lakamsani** [austintgriffith/burner-wallet#26]
- I have an [account with  10 xDAI ](https://blockscout.com/poa/dai/address/0xd4f1a493787a29d38c216f592d4a1c84d89caad1/tokens)
- I have MetaMask 5.0.2 (on my mac book pro with macOS  Mojave 10.14.1, Chrome 70.0.3538.102) set to custom RPC of https://dai.poa.network
- Trying to transfer 9 xDAI to my burner address at 0x5D858916036b1B3D23de7978a30AC9829f86E688 never completes. See attached screenshot. 
<img width="1556" alt="screen shot 2018-11-14 at 11 46 51 am" src="https://user-images.githubusercontent.com/3322496/48515709-4f2bdf80-e816-11e8-9067-344b97cb466a.png">

**Comment by austintgriffith** [comment]
Is this still happening? Maybe it was an issue with POA? I am able to bridge fine.
