### ISSUE TITLE
Local development - https requirement

### ISSUE THREAD

**Issue by johngrantuk** [austintgriffith/burner-wallet#39]
When working locally if you visit http://localhost:3000/ then the app doesn't display. Can be fixed easily by going to https instead so: https://localhost:3000/ 

The Contributing part in the readme probably needs to be updated to show this (happy to do this - just let me know).

I think this is due to the extra -e "HTTPS=true" added to the Docker command.

**Comment by austintgriffith** [comment]
Yeah you can just pull -e "HTTPS=true" out too

It relates to this:
https://github.com/austintgriffith/burner-wallet/pull/33/commits/4e9cbebecaae58deae59402d7ffa0100e19ee391
