### ISSUE TITLE
Create an alternative signed hash. 

### ISSUE THREAD

**Issue by riusricardo** [austintgriffith/burner-wallet#47]
The actual hash requires a destination field. It is not obligatory anymore because there are more parameters that make unique each fund.

The idea is to have a new feature for enhancing the send with link capability. There is no need to know the destination beforehand. If a user is claiming a fund with a link, the app could show a text field to write the destination address. In a future enhancement this could even be an ENS.

**Comment by riusricardo** [comment]
To prevent frontrunning we'll keep the destination in the hash.
The actual link has 2 parts: **claimId + privateKey**

**Comment by riusricardo** [comment]
@austintgriffith We can close this issue. We could think about this later and analyze if there is an alternative or keep it as it is.

**Comment by austintgriffith** [comment]
thanks!
