### ISSUE TITLE
Missing Exchange SC code. React building error.

### ISSUE THREAD

**Issue by riusricardo** [austintgriffith/burner-wallet#52]
`./src/components/Bridge.js
Module not found: Can't resolve '../contracts/Exchange.abi.js' in '/dapp/src/components'`

For testing, I just commented the line 45 on Bridge.js to let it build `abi:require("../contracts/Exchange.abi.js"),`

**Comment by austintgriffith** [comment]
committed this static file to the repo, should fix build errors
