### ISSUE TITLE
Error Bridging DAI to ETH

### ISSUE THREAD

**Issue by austintgriffith** [austintgriffith/burner-wallet#55]
First of all, let's have a prompt that comes up letting them know they don't have any gas and they need to send ETH to the address. 

Second, I got this error when going DAI to ETH:
![screen shot 2019-01-03 at 11 01 15 am](https://user-images.githubusercontent.com/2653167/50653520-06a3bf00-0f47-11e9-993d-fb54dafd3e3c.png)

**Comment by austintgriffith** [comment]
^^ private key if anyone is quick enough ;)

**Comment by jtremback** [comment]
@austintgriffith this may need to be reopened, I have been getting the same error. As you can see, I have Eth: ![screenshot from 2019-01-23 17-35-11](https://user-images.githubusercontent.com/1335122/51648441-6a614c80-1f35-11e9-88f0-e8d1ec7285a3.png)

**Comment by jtremback** [comment]
@austintgriffith I just got this error and it was confusing. Do you still want a prompt? I can add it.
