### ISSUE TITLE
Add apple-touch-icon

### ISSUE THREAD

**Issue by andrewdamelio** [austintgriffith/burner-wallet#58]
I love Burner, just added it to my iPhone home screen but I'm sad there is no 🔥 icon.

<img src="https://user-images.githubusercontent.com/1683736/50704973-3cb87000-1027-11e9-977d-2d836d94c00c.PNG" height="500" />

I'd gladly push a PR if you have any icon assets.

**Comment by TimDaub** [comment]
https://github.com/austintgriffith/burner-wallet/pull/107#issuecomment-477647383 Close.
