### ISSUE TITLE
Network Suggest UX

### ISSUE THREAD

**Issue by austintgriffith** [austintgriffith/burner-wallet#66]
When the network suggest box pops up:
![image](https://user-images.githubusercontent.com/2653167/50769296-c1caa180-1240-11e9-96a4-dca42589445f.png)

It should be copy and pastable content so you can just select "https://dai.poa.network" and paste it into the custom RPC box

**Comment by TimDaub** [comment]
<img width="469" alt="Screen Shot 2019-04-09 at 17 36 34" src="https://user-images.githubusercontent.com/2758453/55814013-11de2c00-5aee-11e9-827f-8ee907c38a1e.png">

That's fixed, isn't it?
