### ISSUE TITLE
Incorrect Units when moving from XDAI to DAI

### ISSUE THREAD

**Issue by dconroy** [austintgriffith/burner-wallet#68]
When removing your XDAI from the burner wallet via the exchange page, you enter the amount of xdai to withdraw in USD, however the metamask popup asks for confirmation in ETH.

Eg, if you try to withdraw 9$ it attempts to withdraw 9 Eth ($1350 at current prices)

video: https://www.dropbox.com/s/pq13ojxyha64qn9/price-in-eth.mov?dl=0

**Comment by dconroy** [comment]
This may just be my misunderstanding, but if the expected behavior of what was recorded above is dai withdrawal and not eth withdrawl - this actually locks the user into xdai with no easy of transferring back...

**Comment by marczeller** [comment]
To the best of my knowledge it's a Metamask UI issue, i "kinda" solved it with the advanced options : 
![image](https://user-images.githubusercontent.com/21088542/50822093-ba7ec300-1328-11e9-9639-373b2a34426c.png)

Resulting in this : https://youtu.be/o_hONcPTC5c
