### ISSUE TITLE
Suggestions for QoL Improvements in development

### ISSUE THREAD

**Issue by blurpesec** [austintgriffith/burner-wallet#70]
Suggestions:
- [ ] A `Contributors.md` to detail layout of the codebase and where things belong.
- [ ] Upgrade to Typescript to support types or remove Typescript types in `src/components/history.js`.
- [ ] Add a `utils` folder for process reuse-ability. JsonRPC/WS stuff is a good example of this: They're pretty standard in how they're conducted, so it could be beneficial to create a `/utils/networkCalls` module for re-use across providers/chains. Next time you need it, you can just import and re-use with a `networkCalls.getAddressBalance( provider, address )` or something like that
- [ ] Remove `console.log()`'s in production. Maybe replace with [Debug](https://www.npmjs.com/package/debug) for development env?
- [ ] [Stop routing based on pathname length](https://github.com/austintgriffith/burner-wallet/issues/70#issuecomment-457444936)

If I think of others, i'll add them :-)

**Comment by jtremback** [comment]
Stop routing based on pathname length...

```
     } else if (window.location.pathname.length == 43) {
        this.changeView("send_to_address");
        console.log("CHANGE VIEW");
      } else if (window.location.pathname.length == 134) {
        let parts = window.location.pathname.split(";");
        let claimId = parts[0].replace("/", "");
        let claimKey = parts[1];
        console.log("DO CLAIM", claimId, claimKey);
        this.setState({ claimId, claimKey });
        window.history.pushState({}, "", "/");
      } else if (
        (window.location.pathname.length >= 65 &&
          window.location.pathname.length <= 67 &&
          window.location.pathname.indexOf(";") < 0) ||
        (window.location.hash.length >= 65 &&
          window.location.hash.length <= 67 &&
          window.location.hash.indexOf(";") < 0)
      ) {
        console.log("incoming private key");
        let privateKey = window.location.pathname.replace("/", "");
        if (window.location.hash) {
          privateKey = window.location.hash;
        }
        privateKey = privateKey.replace("#", "");
        if (privateKey.indexOf("0x") != 0) {
          privateKey = "0x" + privateKey;
        }
        //console.log("!!! possibleNewPrivateKey",privateKey)
        this.setState({ possibleNewPrivateKey: privateKey });
        window.history.pushState({}, "", "/");
      }
```

**Comment by dbe** [comment]
Would love to see PRs for these!

**Comment by TimDaub** [comment]
I created separate issues for this list. We'll add them to sprints eventually. Thanks for your input!

> * A `Contributors.md` to detail layout of the codebase and where things belong.

#202

> Add a utils folder for process reuse-ability. JsonRPC/WS stuff is a good example of this: They're pretty standard in how they're conducted, so it could be beneficial to create a /utils/networkCalls module for re-use across providers/chains. Next time you need it, you can just import and re-use with a networkCalls.getAddressBalance( provider, address ) or something like that

There's currently two design documents, that propose solutions to this:

- https://docs.google.com/document/d/1GtS_NxhxSt9XVTphp4fWRvjeQjIVT8WbYsqpKAlWbfE
- https://github.com/leapdao/burner-wallet/issues/109

Feedback welcome :)

> Remove console.log()'s in production. Maybe replace with Debug for development env?

IMO this is not too big of an issue at this point. Bigger fish to fry.

> * Stop routing based on pathname length

#194. Will soon be fixed.

Closing this for now. Feel free to reopen.
