### ISSUE TITLE
User has lost 5 dollars by wiping history (aka how do we explain the temporary nature of the wallet?)

### ISSUE THREAD

**Issue by jtremback** [austintgriffith/burner-wallet#73]
Someone I was introducing Burner Wallet to had a setting on android chrome which wipes their history when they close the app. Obviously this caused them to lose their money.

I understand this is totally a core tradeoff of Burner Wallet, but bringing this to the general public, it will happen a lot, and people will get mad about no matter how much you explain it. I'm somewhat aware of the functionality on the desktop with metamask, but a lot of our prospective users of burner wallet don't have desktop computers, plus installing metamask is another complicated step so I don't want to rely on it.

Let's brainstorm some solutions:

**Comment by jtremback** [comment]
Instructions on the front page (or a wizard or something) instructing users to screenshot their private key. Then they can recover if they lose their browser history.

**Comment by NukeManDan** [comment]
In whatever method is implemented - consider prompting that the wallet is very hot - not to store large amounts of money! Along with links to better resources for doing so - like installing metamask / a mobile wallet app / buying a hardware wallet as a "savings account". Then integrating easy sweeping to those options (and/or a link to a detailed explainer like a medium post about it)

For ideas to backup: 
- A form to email / text key to you
- a button to download a plain text copy locally
- a prompt to set a seed phrase they can remember to recover w/ information on what that should be (long, non-dictionary words eg. "I love 411 the bufficorns of the gr8 plains! :-)" )

**Comment by jtremback** [comment]
Yea I think that everything necessary is already implemented on the "Advanced" page, just need to make it prominent and have a recommended method.

**Comment by austintgriffith** [comment]
yeah this is a tough one. I can't think of a name better than burner that tells you this is very temporary. 

If you can come up with something we have an open ticket here: https://github.com/austintgriffith/burner-wallet/issues/22

You only lose the private key when local storage is cleared.
