### ISSUE TITLE
Add support for EIP-1613 Relays for 'claim' meta-transactions

### ISSUE THREAD

**Issue by alex-forshtat-tbk** [austintgriffith/burner-wallet#87]
With the current implementation, the user who receives a transfer of funds via a URL link has to make a claim on a blockchain.
In case the user does not have a sufficient amount of native token to perform such a transaction, he can make an HTTP request to the xDai relay server to have that claim made for him.

This creates a centralized single point of failure for Burner Wallet, as the address of such relay is hardcoded and it has no way to look up alternative trusted relays.

EIP 1613 targets this specific use case and solves it in a compatible, yet decentralized way. Its benefits can be achieved by implementing RelayRecipient interface in Links contract and using 'tabookey-gasless' library to perform a 'claim' transaction.

I've made a pull request here https://github.com/austintgriffith/burner-wallet/pull/86 
It contains a minimal implementation that allows a gasless wallet to make a claim from the Links contract using the RelayHub & relay client.

The easiest way to run the relay is in our Docker container:
docker run -p 8090:8090 tabookey/gsn-dev-server:v0.3

Please hit me or Yoav (@yoav-tabookey) up at any time if you have any questions.

**Comment by TimDaub** [comment]
PR #86 was merged. Can someone familiar with the situation comment on whether this issue can hence be closed. Thanks!

**Comment by alex-forshtat-tbk** [comment]
Right, the Burner Wallet has been running with Gas Station Network for some time now. Closing the issue.
