### ISSUE TITLE
Impossible to convert xDai to Dai

### ISSUE THREAD

**Issue by vinsalg** [austintgriffith/burner-wallet#90]
**UPDATE**
After more investigation, it seems the problem stems from when you switch from the main ETH network to the dai.poa.network. You need to be very careful and refresh the page when changing networks, otherwise transactions seems to be sent on the wrong chain resulting in all kinds of problems and stuck funds.

Could something be done to prevent such problems?

---

I have 0.20 in xDai with a metamask address. Using the bridge or inside the app, the transaction gets stuck forever.

The transaction hangs forever:
<img width="938" alt="screen shot 2019-01-28 at 5 18 42 pm" src="https://user-images.githubusercontent.com/12116040/51877645-da027d80-2321-11e9-963f-30b06991055e.png">

Looking at the console, it says the transaction is never mined:
<img width="541" alt="screen shot 2019-01-28 at 5 20 54 pm" src="https://user-images.githubusercontent.com/12116040/51877700-03bba480-2322-11e9-9e57-57d5f9aaefcc.png">

Metamask version: **5.3.2**
Network: https://dai.poa.network

Steps to repeat:
1. Create a new metamask account.
2. Visit xdai.io
3. Click "Receive"
4. Send 0.10 xDai from a burner wallet to the address displayed.
5. Switch Metamask network to the https://dai.poa.network network.
6. Click the arrow and convert the 0.10 xDai to Dai.
7. Send more Eth, Dai and xDai to the wallet.
8. Now the xDai funds are stuck and you can not send or convert them back to Dai.
This only applies when connected with Metamask.

<img width="1235" alt="screen shot 2019-01-28 at 7 29 32 pm" src="https://user-images.githubusercontent.com/12116040/51882263-27d3b180-2333-11e9-8173-be92719896c8.png">

**Comment by igorbarinov** [comment]
Your transaction was ok, it's just UI which stuck.
You can always monitor status of the bridge here https://bridge-monitoring.poa.net/dai/eventsStats

**Comment by igorbarinov** [comment]
Bridge UI could've been maid to avoid this problem. 
Please contribute, at least an issue, here https://github.com/poanetwork/bridge-ui/issues

**Comment by riusricardo** [comment]
> **UPDATE**
> After more investigation, it seems the problem stems from when you switch from the main ETH network to the dai.poa.network. You need to be very careful and refresh the page when changing networks, otherwise transactions seems to be sent on the wrong chain resulting in all kinds of problems and stuck funds.
> 
> Could something be done to prevent such problems?

There are two related issues: 
1) (Reported in Metamask) Pending transaction from a side chain was executed on the mainnet  [#5762](https://github.com/MetaMask/metamask-extension/issues/5762)
2) (Reported in Burner Wallet) Exchanging DAI to Eth  #82

**Comment by vinsalg** [comment]
Fixed for me by [#6044](https://github.com/MetaMask/metamask-extension/pull/6044) on the Metamask side. Be sure to run the latest Metamask v.5.3.3.

Thank you everyone for your help and time.
